### ISSUE TITLE
[Bug]: Error in console in world load re: Permission/Ownership Viewer

### ISSUE THREAD

**Issue by esheyw** [arcanistzed/sidebar-macros#14]
### Expected Behavior

No errors

### Current Behavior

![image](https://i.imgur.com/rY49dHi.png)

### Steps to Reproduce

load a world with both modules active

### Context

Permission Viewer has changed its name to Ownership Viewer, which is what I'm guessing has caused this issue.

### Version

0.8.2

### Foundry VTT Version

10.286

### Operating System

Win10

### Browser / App

Chrome

### Game System

pf2e 4.1.3

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by p4535992** [comment]
i got this error in a linux enviroment too.

**Comment by Doresain** [comment]
Just submitted a PR for this. A few things going on:
- The Permission Viewer module was renamed Ownership Viewer to align core naming convention changes in v10, so the class is now OwnershipViewer - that's what causes this error.
- I tested fixing this, but it turns out OwnershipViewer watches for the renderMacroDirectory hook itself and doesn't need this code - doing it in both places actually duplicates the OV widget on the item.

I dug into the history of PV, and it looks like PV actually accounted for this module itself since, like, Jan of 2020? So maybe this bit of code has actually been duplicating the PV widget on macros for the last 2.5 years and can actually be removed altogether? I don't have a v9 or previous installation anymore and so couldn't easily check this.

**Comment by p4535992** [comment]
hey @arcanistzed sorry to bother can you merge the pr from doresain ?

**Comment by arcanistzed** [comment]
Sorry, for taking so long with this. I have been very busy with school. The PR is merged and I'll make release. Thank you all :)
